#pragma once

#include "game/AttackAction.h"
#include "game/CaptureAction.h"
#include "game/City.h"
#include "game/Faction.h"
#include "game/GameSession.h"
#include "game/MoveAction.h"

#include <cstddef>
#include <cstdint>
#include <string>
#include <variant>
#include <vector>

namespace game {

// ── Event types generated by action processing ─────────────────────────────

/// Types of events that action processing can generate.
enum class ActionEventType : std::uint8_t {
    UnitMoved,
    UnitAttacked,
    UnitKilled,
    CityCaptured,
    FactionEliminated,
    TurnEnded,
    ProductionQueued,
    BuildQueued,
};

/// A single event generated during action processing.
/// Contains enough information for clients to update their view.
struct ActionEvent {
    ActionEventType type{};

    /// Player who caused this event.
    PlayerId playerId = 0;

    /// Unit index involved (if applicable).
    std::size_t unitIndex = 0;

    /// Target unit index (for attacks).
    std::size_t targetUnitIndex = 0;

    /// Tile coordinates (for moves, captures, builds).
    int row = 0;
    int col = 0;

    /// Faction involved (for captures, eliminations).
    FactionId factionId = 0;

    /// Descriptive detail (city name, unit type, error info, etc.).
    std::string detail;
};

// ── Extended action types ──────────────────────────────────────────────────

/// Action to end the current player's turn.
struct EndTurnAction {
    // No parameters needed — the player ID comes from processAction.
};

/// Action to queue unit production in a city.
struct ProduceUnitAction {
    CityId cityId = 0;
    std::string templateKey;
    int productionCost = 0;
};

/// Action to queue building construction in a city.
struct BuildAction {
    CityId cityId = 0;
    std::string buildingType;
    int targetRow = 0;
    int targetCol = 0;
};

/// All action types the processor can handle.
using ActionVariant =
    std::variant<MoveAction, AttackAction, CaptureAction, EndTurnAction, ProduceUnitAction, BuildAction>;

// ── Processing result ──────────────────────────────────────────────────────

/// Result of processing an action through the ActionProcessor pipeline.
struct ProcessedActionResult {
    bool success = false;
    std::string errorMessage;
    std::vector<ActionEvent> events;
};

// ── ActionProcessor ────────────────────────────────────────────────────────

/// Server-side action processing pipeline.
///
/// Receives actions from clients, validates them against the authoritative
/// game state, executes them via existing action classes, and generates
/// result events for broadcast.
///
/// Usage:
///   ActionProcessor processor;
///   auto result = processor.processAction(session, playerId, action);
///   if (result.success) { /* broadcast result.events */ }
class ActionProcessor {
  public:
    /// Process an action submitted by a player.
    ///
    /// Pipeline:
    ///   1. Validate player exists and is connected
    ///   2. Validate action-specific preconditions
    ///   3. Execute action against game state
    ///   4. Generate result events
    ///
    /// Returns a ProcessedActionResult with success/failure, generated events,
    /// and an error message if the action was rejected.
    [[nodiscard]] static ProcessedActionResult processAction(GameSession &session, PlayerId playerId,
                                                             const ActionVariant &action);

  private:
    /// Process a move action.
    [[nodiscard]] static ProcessedActionResult processMove(GameSession &session, PlayerId playerId,
                                                           const MoveAction &action);

    /// Process an attack action.
    [[nodiscard]] static ProcessedActionResult processAttack(GameSession &session, PlayerId playerId,
                                                             const AttackAction &action);

    /// Process a capture action.
    [[nodiscard]] static ProcessedActionResult processCapture(GameSession &session, PlayerId playerId,
                                                              const CaptureAction &action);

    /// Process an end-turn action.
    [[nodiscard]] static ProcessedActionResult processEndTurn(GameSession &session, PlayerId playerId);

    /// Process a produce-unit action.
    [[nodiscard]] static ProcessedActionResult processProduceUnit(GameSession &session, PlayerId playerId,
                                                                  const ProduceUnitAction &action);

    /// Process a build action.
    [[nodiscard]] static ProcessedActionResult processBuild(GameSession &session, PlayerId playerId,
                                                            const BuildAction &action);

    /// Validate that a player is registered and connected.
    [[nodiscard]] static ProcessedActionResult validatePlayer(const GameSession &session, PlayerId playerId);

    /// Check that a unit belongs to the given player's faction.
    [[nodiscard]] static bool unitBelongsToPlayer(const GameSession &session, PlayerId playerId, std::size_t unitIndex);

    /// Check that a city belongs to the given player's faction.
    [[nodiscard]] static bool cityBelongsToPlayer(const GameSession &session, PlayerId playerId, CityId cityId);

    /// Build an error result with a message.
    [[nodiscard]] static ProcessedActionResult makeError(const std::string &message);
};

} // namespace game
